name: Main Deploy
on: 
    workflow_dispatch: 
        inputs:
          build-status:
            description: "Choose the build status for the demo"
            type: choice
            options:
            - success
            - failure        
            default: success

jobs:
    call-build:
        uses: ./.github/workflows/o-workflow.yml
        with: 
             build-status: ${{ inputs.build-status }}
                
    deploy:
        runs-on: ubuntu-latest
        needs: call-build
        if: ${{ needs.call-build.outputs.build-status == 'success' }}
        steps:
          - name: Deploy
            run: echo Deploy
