name: Main Deploy
on: 
    workflow_dispatch: 
        inputs:
          build-status:
            description: "Choose the build status for the demo"
            type: choice
            options:
            - success
            - failure        
            default: success

jobs:
    call-build:
        runs-on: ubuntu-latest
        steps: 
            - name: Llamada
              uses: .github/workflows/o-workflow.yml@main
              with: 
                    build-status: ${{ inputs.build-status }}

        
    deploy:
        runs-on: ubuntu-latest
        needs: call-build
        steps:
          - name: Deploy
            run: echo Deploy