name: Working with reusables

on:
  workflow_call:
    inputs:
      build-status:
        description: "Choose the build status for the demo"
        type: string
        options:
          - success
          - failure  
        required: true      
    outputs: 
      status: ${{ jobs.build.outputs.build-status }}

jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT 

      - name: Build
        id: build
        run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"  
